name = "be-a-good-person-proxy"
main = "worker.ts"
compatibility_date = "2024-07-02"

# Secrets like GITHUB_PAT and TEAM_PASSWORD should be set via:
# wrangler secret put GITHUB_PAT
# wrangler secret put TEAM_PASSWORD
